"use client";

import { attendanceSummaryApi } from "@/services/attendanceSummaryApi";
import dashboardApi from "@/services/dashboardApi";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { CalendarCheck2,CheckCircle2,ClockAlert,Users } from "lucide-react";
import { useState } from "react";

const field = "rounded-lg border border-[var(--card-border)] bg-transparent px-3 py-2 text-sm";
export default function DepartmentAttendancePage() {
  const now = new Date(); const client = useQueryClient();
  const [period, setPeriod] = useState({ year: now.getFullYear(), month: now.getMonth() + 1 });
  const [schedule, setSchedule] = useState({ scheduledDays: 22, weekendDays: 8, holidayDays: 0 });
  const employees = useQuery({ queryKey: ["department-employees"], queryFn: dashboardApi.getEmployees });
  const summaries = useQuery({ queryKey: ["attendance-summaries", period], queryFn: () => attendanceSummaryApi.department(period.year, period.month) });
  const refresh = () => client.invalidateQueries({ queryKey: ["attendance-summaries"] });
  const build = useMutation({ mutationFn: (employeeId: string) => attendanceSummaryApi.build({ employeeId, ...period, ...schedule }), onSuccess: refresh });
  const verify = useMutation({ mutationFn: attendanceSummaryApi.verify, onSuccess: refresh });
  const latest = new Map<string, NonNullable<typeof summaries.data>[number]>();
  summaries.data?.forEach((summary) => { if (!latest.has(summary.employeeId)) latest.set(summary.employeeId, summary); });
  const discrepancyCount = summaries.data?.filter((s) => s.verificationStatus === "Discrepancies").length ?? 0;
  return <main className="mx-auto max-w-7xl space-y-6 p-6 lg:p-8">
    <header><p className="text-xs uppercase tracking-wider text-[var(--text-secondary)]">Department Manager · department restricted</p><h1 className="text-3xl font-bold">Department Attendance</h1><p className="mt-1 text-sm text-[var(--text-secondary)]">Build and verify monthly attendance for employees in your department. Finance receives verified versions automatically.</p></header>
    <section className="grid gap-4 md:grid-cols-3">{[{ label: "Department employees", value: employees.data?.length ?? 0, Icon: Users }, { label: "Verified summaries", value: summaries.data?.filter((s) => s.verificationStatus === "Verified").length ?? 0, Icon: CheckCircle2 }, { label: "Discrepancies", value: discrepancyCount, Icon: ClockAlert }].map(({label,value,Icon}) => <div key={label} className="rounded-2xl border border-[var(--card-border)] bg-[var(--card-dark)] p-5"><Icon className="mb-3 h-5 w-5 text-[#E87332]"/><p className="text-xs uppercase text-[var(--text-secondary)]">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></div>)}</section>
    <section className="grid gap-3 rounded-2xl border border-[var(--card-border)] bg-[var(--card-dark)] p-5 sm:grid-cols-5"><div className="sm:col-span-5"><h2 className="font-semibold">Monthly summary settings</h2><p className="text-xs text-[var(--text-secondary)]">Leave totals remain zero because no approved-leave source API exists.</p></div><input aria-label="Year" className={field} type="number" value={period.year} onChange={(e) => setPeriod({...period, year: Number(e.target.value)})}/><input aria-label="Month" className={field} type="number" min="1" max="12" value={period.month} onChange={(e) => setPeriod({...period, month: Number(e.target.value)})}/><input aria-label="Scheduled days" className={field} type="number" min="0" value={schedule.scheduledDays} onChange={(e) => setSchedule({...schedule, scheduledDays: Number(e.target.value)})}/><input aria-label="Weekend days" className={field} type="number" min="0" value={schedule.weekendDays} onChange={(e) => setSchedule({...schedule, weekendDays: Number(e.target.value)})}/><input aria-label="Holiday days" className={field} type="number" min="0" value={schedule.holidayDays} onChange={(e) => setSchedule({...schedule, holidayDays: Number(e.target.value)})}/></section>
    <section className="rounded-2xl border border-[var(--card-border)] bg-[var(--card-dark)] p-5"><h2 className="flex items-center gap-2 text-lg font-semibold"><CalendarCheck2 className="h-5 w-5 text-[#E87332]"/>Monthly Attendance Summary</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="text-xs uppercase text-[var(--text-secondary)]"><tr><th className="py-2">Employee</th><th>Scheduled</th><th>Worked</th><th>Weekend</th><th>Holiday</th><th>Paid / unpaid leave</th><th>Approved OT</th><th>Missing / disputes</th><th>Version</th><th>Status</th><th>Action</th></tr></thead><tbody>{employees.data?.map((employee) => { const s = latest.get(employee.id); return <tr key={employee.id} className="border-t border-[var(--card-border)]"><td className="py-3"><p className="font-medium">{employee.fullName}</p><p className="text-xs text-[var(--text-secondary)]">{employee.id}</p></td><td>{s?.scheduledDays ?? "–"}</td><td>{s?.workedDays ?? "–"}</td><td>{s?.weekendDays ?? "–"}</td><td>{s?.holidayDays ?? "–"}</td><td>{s ? `${s.approvedPaidLeaveDays} / ${s.approvedUnpaidLeaveDays}` : "–"}</td><td>{s ? `${s.approvedOvertimeHours}h` : "–"}</td><td className={s && (s.missingPunches || s.attendanceDisputes) ? "text-amber-200" : ""}>{s ? `${s.missingPunches} / ${s.attendanceDisputes}` : "–"}</td><td>{s ? `v${s.summaryVersion}` : "–"}</td><td>{s?.verificationStatus ?? "Not built"}</td><td className="space-x-2"><button disabled={build.isPending} onClick={() => build.mutate(employee.id)} className="rounded-lg border border-[var(--card-border)] px-3 py-1 text-xs">{s ? "Rebuild" : "Build"}</button>{s?.verificationStatus === "Draft" && <button disabled={verify.isPending} onClick={() => verify.mutate(s.id)} className="rounded-lg bg-[#2F5C52] px-3 py-1 text-xs text-white">Verify</button>}</td></tr>; })}</tbody></table></div></section>
    {discrepancyCount > 0 && <div className="rounded-xl border border-amber-500/30 bg-amber-500/10 p-4 text-sm text-amber-100">Missing punches must be corrected through the attendance correction API before rebuilding and verifying the summary. Finance cannot calculate payroll from these records.</div>}
  </main>;
}
