apiVersion: v1
kind: Secret
metadata:
  name: smarthotel-secrets
  namespace: smarthotel-staging
type: Opaque
stringData:
  postgres-user: REPLACE_AT_DEPLOY_TIME
  postgres-password: REPLACE_AT_DEPLOY_TIME
  identity-connection: REPLACE_AT_DEPLOY_TIME
  booking-connection: REPLACE_AT_DEPLOY_TIME
  hotelops-connection: REPLACE_AT_DEPLOY_TIME
  notifications-connection: REPLACE_AT_DEPLOY_TIME
  rabbitmq-user: REPLACE_AT_DEPLOY_TIME
  rabbitmq-password: REPLACE_AT_DEPLOY_TIME
  redis-password: REPLACE_AT_DEPLOY_TIME
  redis-connection: REPLACE_AT_DEPLOY_TIME
  hotelops-api-key: REPLACE_AT_DEPLOY_TIME
  biometrics-api-key: REPLACE_AT_DEPLOY_TIME
  payhere-sandbox-id: REPLACE_AT_DEPLOY_TIME
  payhere-sandbox-secret: REPLACE_AT_DEPLOY_TIME
  supabase-url: REPLACE_AT_DEPLOY_TIME
  supabase-key: REPLACE_AT_DEPLOY_TIME
