package com.smarthotel.fieldops.service;
import com.smarthotel.fieldops.domain.model.*; import com.smarthotel.fieldops.domain.model.LeaveRequest.Status; import com.smarthotel.fieldops.domain.model.enums.TaskEnums.TaskRole; import com.smarthotel.fieldops.domain.repository.*; import com.smarthotel.fieldops.dto.LeaveDtos.*; import org.junit.jupiter.api.*; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.*; import java.time.*; import java.util.*; import static org.assertj.core.api.Assertions.*; import static org.mockito.Mockito.*;
@ExtendWith(org.mockito.junit.jupiter.MockitoExtension.class)
class LeaveServiceTest {
 @Mock LeaveRequestRepository requests; @Mock LeavePolicyRepository policies; @Mock LeaveAuditLogRepository audit; @Mock EmployeeProfileRepository employees; @Mock AttendanceSummaryService summaries; LeaveService service;
 UUID employee=UUID.randomUUID(),department=UUID.randomUUID(),policyId=UUID.randomUUID();
 @BeforeEach void setup(){service=new LeaveService(requests,policies,audit,employees,summaries);lenient().when(requests.save(any())).thenAnswer(i->i.getArgument(0));lenient().when(audit.save(any())).thenAnswer(i->i.getArgument(0));}
 @Test void employeeSubmitsUsingEffectiveConfiguredPolicy(){when(employees.findLockedByEmployeeId(employee)).thenReturn(Optional.of(profile()));when(policies.effective(policyId,LocalDate.of(2026,9,2))).thenReturn(Optional.of(policy(true)));when(requests.overlapping(any(),any(),any(),any())).thenReturn(List.of());LeaveRequest leave=service.submit(employee,new SubmitRequest(policyId,LocalDate.of(2026,9,2),LocalDate.of(2026,9,3),"Family"));assertThat(leave.isPaid()).isTrue();assertThat(leave.getStatus()).isEqualTo(Status.Pending);verify(audit).save(any());}
 @Test void duplicateOverlapIsRejected(){when(employees.findLockedByEmployeeId(employee)).thenReturn(Optional.of(profile()));when(policies.effective(any(),any())).thenReturn(Optional.of(policy(false)));when(requests.overlapping(any(),any(),any(),any())).thenReturn(List.of(LeaveRequest.builder().build()));assertThatThrownBy(()->service.submit(employee,new SubmitRequest(policyId,LocalDate.of(2026,9,2),LocalDate.of(2026,9,3),"Overlap"))).isInstanceOf(IllegalStateException.class);}
 @Test void managerCannotCrossDepartmentOrSelfApprove(){LeaveRequest leave=pending();when(requests.findById(leave.getId())).thenReturn(Optional.of(leave));assertThatThrownBy(()->service.decide(leave.getId(),UUID.randomUUID(),UUID.randomUUID(),new DecisionRequest(true,"ok"))).isInstanceOf(SecurityException.class);assertThatThrownBy(()->service.decide(leave.getId(),employee,department,new DecisionRequest(true,"ok"))).isInstanceOf(SecurityException.class);}
 @Test void approvalInvalidatesEverySpannedPayrollMonth(){LeaveRequest leave=pending();leave.setStartDate(LocalDate.of(2026,8,30));leave.setEndDate(LocalDate.of(2026,10,2));when(requests.findById(leave.getId())).thenReturn(Optional.of(leave));service.decide(leave.getId(),UUID.randomUUID(),department,new DecisionRequest(true,"approved"));verify(summaries,times(3)).markOutdated(eq(employee),any());}
 private EmployeeProfile profile(){return EmployeeProfile.builder().employeeId(employee).departmentId(department).fullName("Employee").role(TaskRole.Staff).build();} private LeavePolicy policy(boolean paid){return LeavePolicy.builder().id(policyId).leaveType("Configured").paid(paid).effectiveFrom(LocalDate.of(2026,1,1)).build();} private LeaveRequest pending(){return LeaveRequest.builder().id(UUID.randomUUID()).employeeId(employee).departmentId(department).policyId(policyId).leaveType("Configured").startDate(LocalDate.of(2026,9,1)).endDate(LocalDate.of(2026,9,2)).reason("Reason").status(Status.Pending).build();}
}
