"use client";

import { salaryPayrollApi } from "@/services/salaryPayrollApi";
import { useQuery } from "@tanstack/react-query";
import { Banknote,Download,ReceiptText,WalletCards } from "lucide-react";

const money = (value: number, currency = "LKR") => new Intl.NumberFormat("en-LK", { style: "currency", currency }).format(value);
const label = (value: string | number) => String(value).replace(/([a-z])([A-Z])/g, "$1 $2");

export default function MySalaryPage() {
  const salary = useQuery({ queryKey: ["my-salary"], queryFn: salaryPayrollApi.mine, retry: false });
  const download = async (id: string) => { const blob = await salaryPayrollApi.payslip(id); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `payslip-${id}.pdf`; anchor.click(); URL.revokeObjectURL(url); };
  const current = salary.data?.current;
  return <main className="mx-auto max-w-7xl space-y-6 p-6 lg:p-8">
    <header><p className="text-xs uppercase tracking-wider text-[var(--text-secondary)]">Employee self-service · private</p><h1 className="text-3xl font-bold">My Salary</h1><p className="mt-1 text-sm text-[var(--text-secondary)]">Your approved salary, allowances, payslips and simulated payment status.</p></header>
    {salary.isError && <div className="rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-200">Your salary information could not be loaded.</div>}
    <section className="grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-[var(--card-border)] bg-[var(--card-dark)] p-5"><Banknote className="mb-3 h-5 w-5 text-[#E87332]"/><p className="text-xs uppercase text-[var(--text-secondary)]">Current basic salary</p><p className="mt-1 text-2xl font-bold">{current ? money(current.baseSalary, current.currency) : "Not available"}</p></div><div className="rounded-2xl border border-[var(--card-border)] bg-[var(--card-dark)] p-5"><WalletCards className="mb-3 h-5 w-5 text-[#E87332]"/><p className="text-xs uppercase text-[var(--text-secondary)]">Allowance rules</p><p className="mt-1 text-2xl font-bold">{salary.data?.allowances.length ?? 0}</p></div><div className="rounded-2xl border border-[var(--card-border)] bg-[var(--card-dark)] p-5"><ReceiptText className="mb-3 h-5 w-5 text-[#E87332]"/><p className="text-xs uppercase text-[var(--text-secondary)]">Payslips</p><p className="mt-1 text-2xl font-bold">{salary.data?.payrolls.length ?? 0}</p></div></section>
    <section className="rounded-2xl border border-[var(--card-border)] bg-[var(--card-dark)] p-5"><h2 className="text-lg font-semibold">My allowances</h2><div className="mt-3 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{salary.data?.allowances.map((a) => <div key={a.id} className="rounded-xl border border-[var(--card-border)] p-3"><p className="font-medium">{label(a.kind)}</p><p className="text-sm text-[var(--text-secondary)]">{label(a.calculationType)} · {a.calculationType === "PercentageOfBasic" ? `${a.value}%` : money(a.value, a.currency)}</p></div>)}{!salary.isLoading && !salary.data?.allowances.length && <p className="text-sm text-[var(--text-secondary)]">No current allowance rules.</p>}</div></section>
    <section className="rounded-2xl border border-[var(--card-border)] bg-[var(--card-dark)] p-5"><h2 className="text-lg font-semibold">Itemized payslips & payment status</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="text-xs uppercase text-[var(--text-secondary)]"><tr><th className="py-2">Period</th><th>Basic</th><th>Allowances</th><th>Overtime</th><th>Gross</th><th>Deductions</th><th>Net salary</th><th>Status</th><th>Payslip</th></tr></thead><tbody>{salary.data?.payrolls.map((p) => { const payment = salary.data?.payments.find((x) => x.payrollId === p.id); return <tr key={p.id} className="border-t border-[var(--card-border)]"><td className="py-3">{p.periodStart} – {p.periodEnd}</td><td>{money(p.baseSalary, p.currency)}</td><td>{money(p.allowances, p.currency)}</td><td>{money(p.overtimePay, p.currency)} <span className="text-xs text-[var(--text-secondary)]">({p.overtimeHours}h)</span></td><td>{money(p.grossSalary, p.currency)}</td><td>{money(p.deductions, p.currency)}</td><td className="font-semibold">{money(p.netSalary, p.currency)}</td><td>{payment ? `Mock: ${label(payment.status)}` : label(p.status)}</td><td><button disabled={String(p.status) !== "Disbursed" && p.status !== 6} onClick={() => void download(p.id)} className="flex items-center gap-1 rounded-lg border border-[var(--card-border)] px-3 py-1 text-xs hover:border-[#C4622D] disabled:opacity-40"><Download className="h-3 w-3"/>PDF</button></td></tr>; })}</tbody></table>{!salary.isLoading && !salary.data?.payrolls.length && <p className="py-8 text-center text-sm text-[var(--text-secondary)]">No payslips are available yet.</p>}</div></section>
  </main>;
}
