# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: booking.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'booking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbooking.proto\x12\x07\x62ooking\"(\n\x11\x41\x63tiveStayRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\"u\n\x12\x41\x63tiveStayResponse\x12\x17\n\x0fhas_active_stay\x18\x01 \x01(\x08\x12\x13\n\x0broom_number\x18\x02 \x01(\t\x12\x16\n\x0e\x63heck_out_date\x18\x03 \x01(\t\x12\x19\n\x11\x62ooking_reference\x18\x04 \x01(\t2W\n\x0b\x42ookingGrpc\x12H\n\rGetActiveStay\x12\x1a.booking.ActiveStayRequest\x1a\x1b.booking.ActiveStayResponseB\x1a\xaa\x02\x17SmartHotel.Booking.Grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'booking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\027SmartHotel.Booking.Grpc'
  _globals['_ACTIVESTAYREQUEST']._serialized_start=26
  _globals['_ACTIVESTAYREQUEST']._serialized_end=66
  _globals['_ACTIVESTAYRESPONSE']._serialized_start=68
  _globals['_ACTIVESTAYRESPONSE']._serialized_end=185
  _globals['_BOOKINGGRPC']._serialized_start=187
  _globals['_BOOKINGGRPC']._serialized_end=274
# @@protoc_insertion_point(module_scope)
