"use client";

import { dashboardApi,type ApprovalRequestDto } from "@/services/dashboardApi";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { BadgeCheck,Check,Clock,Loader2,X,XCircle } from "lucide-react";
import { useState } from "react";

function RejectModal({ request, onClose, onConfirm, loading }: { request: ApprovalRequestDto; onClose: () => void; onConfirm: () => void; loading: boolean }) {
  return <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm"><div className="bg-[var(--card-dark)] rounded-2xl border border-[var(--card-border)] shadow-2xl w-full max-w-md"><div className="flex items-center justify-between p-6 border-b border-[var(--card-border)]"><h2 className="font-bold text-[var(--text-primary)]" style={{ fontFamily: "var(--font-fraunces), serif" }}>Reject Request</h2><button onClick={onClose} className="p-1.5 rounded-lg hover:bg-[var(--text-primary)]/8 text-[var(--text-secondary)]"><X className="w-4 h-4" /></button></div><div className="p-6 space-y-5"><p className="text-sm text-[var(--text-secondary)]">Reject <span className="font-medium text-[var(--text-primary)]">{request.type}</span> requested by {request.requestedBy}?</p><div className="flex justify-end gap-3"><button onClick={onClose} className="px-4 py-2 text-sm text-[var(--text-secondary)]">Cancel</button><button onClick={onConfirm} disabled={loading} className="flex items-center gap-2 px-5 py-2 text-sm font-medium bg-[#C4622D] hover:bg-[#E07A3E] text-white rounded-xl transition-colors disabled:opacity-60">{loading && <Loader2 className="w-3.5 h-3.5 animate-spin" />}Reject</button></div></div></div></div>;
}

function ApprovalCard({ request, onApprove, onReject, busy }: { request: ApprovalRequestDto; onApprove: () => void; onReject: () => void; busy: boolean }) {
  const status = request.status;
  const statusStyle = status === "Active" ? "bg-[#2F5C52]/15 text-[#2F5C52] border-[#2F5C52]/30" : status === "Rejected" ? "bg-[#C4622D]/15 text-[#C4622D]/70 border-[#C4622D]/20 line-through" : "bg-[#C4622D]/10 text-[#C4622D] border-[#C4622D]/30";
  const StatusIcon = status === "Active" ? BadgeCheck : status === "Rejected" ? XCircle : Clock;
  return <div className="p-5 bg-[var(--card-dark)] border border-[var(--card-border)] rounded-2xl space-y-4 hover:shadow-md transition-shadow"><div className="flex items-start justify-between gap-3"><div><h3 className="text-sm font-semibold text-[var(--text-primary)]">{request.type}</h3><p className="text-xs text-[var(--text-secondary)] mt-1">{request.description}</p></div><span className={`inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-medium border ${statusStyle}`}><StatusIcon className="w-3 h-3" />{status}</span></div><p className="text-xs text-[var(--text-secondary)]">Requested by <span className="font-medium text-[var(--text-primary)]">{request.requestedBy}</span> · {new Date(request.createdAtUtc).toLocaleDateString()}</p>{status === "PendingApproval" && <div className="flex gap-2"><button onClick={onApprove} disabled={busy} className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium bg-[#2F5C52]/10 hover:bg-[#2F5C52]/20 text-[#2F5C52] border border-[#2F5C52]/20 rounded-xl transition-colors disabled:opacity-60">{busy ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Check className="w-3.5 h-3.5" />}Approve</button><button onClick={onReject} disabled={busy} className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium bg-[#C4622D]/10 hover:bg-[#C4622D]/20 text-[#C4622D] border border-[#C4622D]/20 rounded-xl transition-colors disabled:opacity-60"><X className="w-3.5 h-3.5" />Reject</button></div>}</div>;
}

export default function OwnerApprovalsPage() {
  const queryClient = useQueryClient();
  const [rejecting, setRejecting] = useState<ApprovalRequestDto | null>(null);
  const { data = [], isLoading } = useQuery({ queryKey: ["approval-requests"], queryFn: () => dashboardApi.getApprovalRequests() });
  const mutation = useMutation({ mutationFn: ({ id, action }: { id: string; action: "approve" | "reject" }) => action === "approve" ? dashboardApi.approveApprovalRequest(id) : dashboardApi.rejectApprovalRequest(id), onSuccess: async () => { setRejecting(null); await queryClient.invalidateQueries({ queryKey: ["approval-requests"] }); } });
  return <div className="p-6 lg:p-8 max-w-5xl mx-auto space-y-6"><div><h1 className="text-3xl font-bold text-[var(--text-primary)] tracking-tight" style={{ fontFamily: "var(--font-fraunces), serif" }}>Approvals</h1><p className="text-sm text-[var(--text-secondary)] mt-1">Review pending executive approval requests</p></div>{isLoading ? <div className="space-y-3">{[...Array(4)].map((_, index) => <div key={index} className="h-32 bg-[var(--card-dark)] border border-[var(--card-border)] rounded-2xl animate-pulse" />)}</div> : data.length === 0 ? <div className="py-20 text-center text-sm text-[var(--text-secondary)]">No approval requests.</div> : <div className="space-y-3">{data.map((request) => <ApprovalCard key={request.id} request={request} busy={mutation.isPending && mutation.variables?.id === request.id} onApprove={() => mutation.mutate({ id: request.id, action: "approve" })} onReject={() => setRejecting(request)} />)}</div>}{rejecting && <RejectModal request={rejecting} onClose={() => setRejecting(null)} loading={mutation.isPending} onConfirm={() => mutation.mutate({ id: rejecting.id, action: "reject" })} />}</div>;
}
