# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    from . import hotelops_pb2 as hotelops__pb2
except ImportError:
    import hotelops_pb2 as hotelops__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hotelops_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HotelOpsGrpcStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRoomTypeAvailability = channel.unary_unary(
                '/hotelops.HotelOpsGrpc/GetRoomTypeAvailability',
                request_serializer=hotelops__pb2.RoomTypeAvailabilityRequest.SerializeToString,
                response_deserializer=hotelops__pb2.RoomTypeAvailabilityResponse.FromString,
                _registered_method=True)


class HotelOpsGrpcServicer:
    """Missing associated documentation comment in .proto file."""

    def GetRoomTypeAvailability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HotelOpsGrpcServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRoomTypeAvailability': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoomTypeAvailability,
                    request_deserializer=hotelops__pb2.RoomTypeAvailabilityRequest.FromString,
                    response_serializer=hotelops__pb2.RoomTypeAvailabilityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hotelops.HotelOpsGrpc', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hotelops.HotelOpsGrpc', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HotelOpsGrpc:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRoomTypeAvailability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hotelops.HotelOpsGrpc/GetRoomTypeAvailability',
            hotelops__pb2.RoomTypeAvailabilityRequest.SerializeToString,
            hotelops__pb2.RoomTypeAvailabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
