# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hotelops.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'hotelops.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ehotelops.proto\x12\x08hotelops\"3\n\x1bRoomTypeAvailabilityRequest\x12\x14\n\x0croom_type_id\x18\x01 \x01(\t\"\x9c\x01\n\x1cRoomTypeAvailabilityResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x12\x14\n\x0cis_published\x18\x02 \x01(\x08\x12\x10\n\x08\x63\x61pacity\x18\x03 \x01(\x05\x12\x17\n\x0fprice_per_night\x18\x04 \x01(\x01\x12\x14\n\x0c\x63leaning_fee\x18\x05 \x01(\x01\x12\x15\n\ramenities_fee\x18\x06 \x01(\x01\x32x\n\x0cHotelOpsGrpc\x12h\n\x17GetRoomTypeAvailability\x12%.hotelops.RoomTypeAvailabilityRequest\x1a&.hotelops.RoomTypeAvailabilityResponseB\x1b\xaa\x02\x18SmartHotel.HotelOps.Grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hotelops_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\030SmartHotel.HotelOps.Grpc'
  _globals['_ROOMTYPEAVAILABILITYREQUEST']._serialized_start=28
  _globals['_ROOMTYPEAVAILABILITYREQUEST']._serialized_end=79
  _globals['_ROOMTYPEAVAILABILITYRESPONSE']._serialized_start=82
  _globals['_ROOMTYPEAVAILABILITYRESPONSE']._serialized_end=238
  _globals['_HOTELOPSGRPC']._serialized_start=240
  _globals['_HOTELOPSGRPC']._serialized_end=360
# @@protoc_insertion_point(module_scope)
