"use client";

import { dashboardApi } from "@/services/dashboardApi";
import { useQuery } from "@tanstack/react-query";

export default function StaffOversightPage() {
  const { data = [], isLoading } = useQuery({ queryKey: ["staff-oversight"], queryFn: () => dashboardApi.getStaffOversight() });
  return <div className="p-6 lg:p-8 max-w-7xl mx-auto space-y-6"><div><h1 className="text-3xl font-bold text-[var(--text-primary)] tracking-tight" style={{ fontFamily: "var(--font-fraunces), serif" }}>Staff Oversight</h1><p className="text-sm text-[var(--text-secondary)] mt-1">Read-only manager and team performance roll-up</p></div><div className="bg-[var(--card-dark)] border border-[var(--card-border)] rounded-2xl overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-[var(--card-border)]">{["Manager", "Department", "Team Size", "Task Completion"].map((heading) => <th key={heading} className="px-4 py-3 text-left text-xs font-semibold text-[var(--text-secondary)] uppercase tracking-wider">{heading}</th>)}</tr></thead><tbody>{isLoading ? [...Array(4)].map((_, index) => <tr key={index} className="border-b border-[var(--card-border)] animate-pulse">{[...Array(4)].map((__, cell) => <td key={cell} className="px-4 py-3"><div className="h-4 bg-[var(--text-primary)]/8 rounded w-3/4" /></td>)}</tr>) : data.map((row) => <tr key={row.managerId} className="border-b border-[var(--card-border)] hover:bg-[var(--text-primary)]/2 transition-colors"><td className="px-4 py-3 font-medium text-[var(--text-primary)]">{row.managerName}</td><td className="px-4 py-3 text-[var(--text-secondary)]">{row.departmentName}</td><td className="px-4 py-3 text-[var(--text-secondary)]">{row.teamSize}</td><td className="px-4 py-3"><span className="px-2.5 py-0.5 rounded-full text-xs font-medium border bg-[#2F5C52]/15 text-[#2F5C52] border-[#2F5C52]/30">{row.taskCompletionRate == null ? "No assigned tasks" : `${row.taskCompletionRate.toFixed(0)}%`}</span></td></tr>)}</tbody></table></div></div></div>;
}
