package com.smarthotel.fieldops.service;
import com.smarthotel.fieldops.domain.model.*; import com.smarthotel.fieldops.domain.model.LeaveRequest.Status; import com.smarthotel.fieldops.domain.repository.*; import com.smarthotel.fieldops.dto.LeaveDtos.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;

@Service @RequiredArgsConstructor
public class LeaveService {
 private final LeaveRequestRepository requests; private final LeavePolicyRepository policies; private final LeaveAuditLogRepository audit; private final EmployeeProfileRepository employees; private final AttendanceSummaryService summaries;
 @Transactional public LeaveRequest submit(UUID employeeId, SubmitRequest input) {
   EmployeeProfile employee=employees.findLockedByEmployeeId(employeeId).orElseThrow(()->new IllegalArgumentException("Employee profile not found."));
   if(input.endDate().isBefore(input.startDate())) throw new IllegalArgumentException("Leave end date must not precede start date.");
   LeavePolicy policy=policies.effective(input.policyId(),input.startDate()).orElseThrow(()->new IllegalArgumentException("No active leave policy applies to the requested dates."));
   if(policy.getEffectiveTo()!=null && input.endDate().isAfter(policy.getEffectiveTo())) throw new IllegalArgumentException("Leave request extends beyond the selected policy's effective period.");
   if(!requests.overlapping(employeeId,input.startDate(),input.endDate(),List.of(Status.Pending,Status.Approved)).isEmpty()) throw new IllegalStateException("An overlapping pending or approved leave request already exists.");
   LeaveRequest leave=LeaveRequest.builder().employeeId(employeeId).departmentId(employee.getDepartmentId()).policyId(policy.getId()).leaveType(policy.getLeaveType()).paid(policy.isPaid()).startDate(input.startDate()).endDate(input.endDate()).reason(input.reason().trim()).build(); requests.save(leave); log(leave,employeeId,"Submitted","Employee leave request submitted"); return leave;
 }
 @Transactional public LeaveRequest decide(UUID id,UUID managerId,UUID managerDepartment,DecisionRequest input) {
   LeaveRequest leave=requests.findById(id).orElseThrow(()->new IllegalArgumentException("Leave request not found."));
   if(!managerDepartment.equals(leave.getDepartmentId())) throw new SecurityException("Cross-department leave approval is forbidden."); if(managerId.equals(leave.getEmployeeId())) throw new SecurityException("Employees cannot approve their own leave."); if(leave.getStatus()!=Status.Pending) throw new IllegalStateException("Only pending leave can be decided.");
   leave.setStatus(input.approve()?Status.Approved:Status.Rejected); leave.setDecisionManagerId(managerId); leave.setDecisionReason(input.reason().trim()); leave.setDecidedAt(Instant.now()); leave.setUpdatedAt(Instant.now()); requests.save(leave); log(leave,managerId,input.approve()?"Approved":"Rejected",input.reason()); if(input.approve()) invalidate(leave); return leave;
 }
 @Transactional public LeaveRequest cancel(UUID id,UUID employeeId) { LeaveRequest leave=requests.findById(id).orElseThrow(()->new IllegalArgumentException("Leave request not found.")); if(!leave.getEmployeeId().equals(employeeId)) throw new SecurityException("Another employee's leave cannot be cancelled."); if(leave.getStatus()==Status.Rejected||leave.getStatus()==Status.Cancelled) throw new IllegalStateException("Leave cannot be cancelled in its current status."); boolean wasApproved=leave.getStatus()==Status.Approved; leave.setStatus(Status.Cancelled); leave.setUpdatedAt(Instant.now()); requests.save(leave); log(leave,employeeId,"Cancelled","Employee cancelled leave"); if(wasApproved) invalidate(leave); return leave; }
 @Transactional public LeavePolicy configure(UUID ownerId,PolicyRequest input) { if(input.effectiveTo()!=null&&input.effectiveTo().isBefore(input.effectiveFrom())) throw new IllegalArgumentException("Invalid policy effective dates."); return policies.save(LeavePolicy.builder().leaveType(input.leaveType().trim()).paid(input.paid()).effectiveFrom(input.effectiveFrom()).effectiveTo(input.effectiveTo()).configuredByOwnerId(ownerId).build()); }
 @Transactional(readOnly=true) public List<LeaveRequest> mine(UUID employeeId){return requests.findByEmployeeIdOrderByCreatedAtDesc(employeeId);} @Transactional(readOnly=true) public List<LeaveRequest> department(UUID department){return requests.findByDepartmentIdOrderByCreatedAtDesc(department);} @Transactional(readOnly=true) public List<LeaveRequest> allLeaves(){return requests.findAll();} @Transactional(readOnly=true) public List<LeavePolicy> activePolicies(){return policies.findByActiveTrueOrderByLeaveTypeAsc();}
 @Transactional(readOnly=true) public List<LeaveRequest> approved(UUID employeeId,LocalDate start,LocalDate end){return requests.approvedForPeriod(employeeId,start,end);}
 private void invalidate(LeaveRequest leave){ YearMonth cursor=YearMonth.from(leave.getStartDate()),end=YearMonth.from(leave.getEndDate()); while(!cursor.isAfter(end)){ summaries.markOutdated(leave.getEmployeeId(),cursor.atDay(1)); cursor=cursor.plusMonths(1); } }
 private void log(LeaveRequest leave,UUID actor,String action,String details){audit.save(LeaveAuditLog.builder().leaveRequestId(leave.getId()).actorId(actor).action(action).details(details).build());}
}
