"use client";

import { attendanceSummaryApi } from "@/services/attendanceSummaryApi";
import { financeApi } from "@/services/financeApi";
import { salaryPayrollApi } from "@/services/salaryPayrollApi";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import type { LucideIcon } from "lucide-react";
import { Banknote,Clock3,ShieldCheck,TriangleAlert } from "lucide-react";

const labels = ["Pending verification", "Manager review", "Owner approval", "Approved", "Rejected", "Payment pending", "Mock paid", "Payment failed"];
const status = (value: string | number) => typeof value === "number" ? labels[value] ?? String(value) : String(value).replace(/([a-z])([A-Z])/g, "$1 $2");
const paymentStatus = (value: string | number) => value === 1 || value === "MockPaid" ? "Simulated Payment Completed" : status(value);
const money = (value: number, currency = "LKR") => new Intl.NumberFormat("en-LK", { style: "currency", currency }).format(value);

export default function PayrollPage() {
  const client = useQueryClient();
  const payroll = useQuery({ queryKey: ["finance-payroll"], queryFn: financeApi.payroll, retry: false });
  const payments = useQuery({ queryKey: ["mock-payroll-payments"], queryFn: salaryPayrollApi.payments, retry: false });
  const attendance = useQuery({ queryKey: ["finance-verified-attendance"], queryFn: attendanceSummaryApi.verified, retry: false });
  const calculate = useMutation({ mutationFn: salaryPayrollApi.calculate, onSuccess: async () => { await client.invalidateQueries({ queryKey: ["finance-payroll"] }); } });
  const process = useMutation({ mutationFn: ({ id, scenario }: { id: string; scenario: "Success" | "Failure" | "Timeout" | "DelayedSuccess" }) => salaryPayrollApi.processPayment(id, scenario), onSuccess: async () => { await client.invalidateQueries({ queryKey: ["finance-payroll"] }); await client.invalidateQueries({ queryKey: ["mock-payroll-payments"] }); } });
  const confirm = useMutation({ mutationFn: salaryPayrollApi.confirmDelayed, onSuccess: async () => { await client.invalidateQueries({ queryKey: ["finance-payroll"] }); await client.invalidateQueries({ queryKey: ["mock-payroll-payments"] }); } });
  const approved = payroll.data?.filter((p) => p.status === 3 || String(p.status) === "Approved" || p.status === 7 || String(p.status) === "Failed").length ?? 0;
  const cards: { label: string; value: number; Icon: LucideIcon }[] = [{ label: "Payroll records", value: payroll.data?.length ?? 0, Icon: Banknote }, { label: "Ready / retryable", value: approved, Icon: ShieldCheck }, { label: "Mock payment attempts", value: payments.data?.length ?? 0, Icon: Clock3 }];
  return <main className="mx-auto max-w-7xl space-y-6 p-6 lg:p-8">
    <header><p className="text-xs uppercase tracking-wider text-[var(--text-secondary)]">Finance Department · restricted workflow</p><h1 className="text-3xl font-bold">Payroll & Mock Payments</h1><p className="mt-1 text-sm text-[var(--text-secondary)]">Prepare, verify and process salary payments after mandatory Owner approval.</p></header>
    <div className="rounded-xl border border-amber-500/30 bg-amber-500/10 p-4 text-sm text-amber-100"><strong>Simulation only.</strong> Mock payroll transactions do not transfer real funds or connect to a bank.</div>
    <section className="grid gap-4 md:grid-cols-3">{cards.map(({ label, value, Icon }) => <div key={label} className="rounded-2xl border border-[var(--card-border)] bg-[var(--card-dark)] p-5"><Icon className="mb-3 h-5 w-5 text-[#E87332]"/><p className="text-xs uppercase text-[var(--text-secondary)]">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></div>)}</section>
    {(payroll.isError || payments.isError) && <div className="flex gap-2 rounded-xl border border-amber-500/30 p-4 text-sm text-amber-200"><TriangleAlert className="h-5 w-5"/>This account does not have the required payroll permission.</div>}
    <section className="rounded-2xl border border-[var(--card-border)] bg-[var(--card-dark)] p-5"><h2 className="text-lg font-semibold">Verified Attendance</h2><p className="text-xs text-[var(--text-secondary)]">Read-only Department Manager summaries. Finance cannot edit attendance totals.</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="text-xs uppercase text-[var(--text-secondary)]"><tr><th className="py-2">Employee</th><th>Period</th><th>Worked / scheduled</th><th>Weekend / holiday</th><th>Paid / unpaid leave</th><th>Approved OT</th><th>Version</th><th>Payroll status</th></tr></thead><tbody>{attendance.data?.map((s) => { const existing = payroll.data?.find((p) => p.sourcePayrollId === s.id); return <tr key={s.id} className="border-t border-[var(--card-border)]"><td className="py-3">{s.employeeId}</td><td>{s.payrollYear}-{String(s.payrollMonth).padStart(2,"0")}</td><td>{s.workedDays} / {s.scheduledDays}</td><td>{s.weekendDays} / {s.holidayDays}</td><td>{s.approvedPaidLeaveDays} / {s.approvedUnpaidLeaveDays}</td><td>{s.approvedOvertimeHours}h</td><td>v{s.summaryVersion}</td><td>{existing ? status(existing.status) : <button disabled={calculate.isPending} onClick={() => calculate.mutate(s)} className="rounded-lg bg-[#C4622D] px-3 py-1 text-xs text-white">Calculate payroll</button>}</td></tr>; })}</tbody></table>{!attendance.isLoading && !attendance.data?.length && <p className="py-6 text-center text-sm text-[var(--text-secondary)]">No Manager-verified attendance is awaiting payroll.</p>}</div></section>
    <section className="rounded-2xl border border-[var(--card-border)] bg-[var(--card-dark)] p-5"><h2 className="text-lg font-semibold">Salary verification & payment queue</h2><p className="text-xs text-[var(--text-secondary)]">Itemized values come from the immutable salary and manager-verified attendance snapshot.</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[1200px] text-left text-sm"><thead className="text-xs uppercase text-[var(--text-secondary)]"><tr><th className="py-2">Employee</th><th>Period</th><th>Basic</th><th>Allowances</th><th>Overtime</th><th>Gross</th><th>Deductions</th><th>Net</th><th>Approval</th><th>Mock action</th></tr></thead><tbody>{payroll.data?.map((p) => { const canPay = p.status === 3 || String(p.status) === "Approved" || p.status === 7 || String(p.status) === "Failed"; return <tr key={p.id} className="border-t border-[var(--card-border)]"><td className="py-3 font-medium">{p.employeeId}</td><td>{p.periodStart} – {p.periodEnd}</td><td>{money(p.baseSalary, p.currency)}</td><td>{money(p.allowances, p.currency)}</td><td>{money(p.overtimePay, p.currency)}</td><td>{money(p.grossSalary, p.currency)}</td><td>{money(p.deductions, p.currency)}</td><td className="font-semibold">{money(p.netSalary, p.currency)}</td><td><span className="rounded-full bg-white/5 px-2 py-1 text-xs">{status(p.status)}</span></td><td><div className="flex flex-wrap gap-2"><button disabled={!canPay || process.isPending} onClick={() => process.mutate({ id: p.id, scenario: "Success" })} className="rounded-lg bg-[#2F5C52] px-3 py-1 text-xs text-white disabled:opacity-40">Mock pay</button><button disabled={!canPay || process.isPending} onClick={() => process.mutate({ id: p.id, scenario: "Failure" })} className="rounded-lg border border-red-500/40 px-3 py-1 text-xs text-red-200 disabled:opacity-40">Failure</button><button disabled={!canPay || process.isPending} onClick={() => process.mutate({ id: p.id, scenario: "Timeout" })} className="rounded-lg border border-amber-500/40 px-3 py-1 text-xs text-amber-100 disabled:opacity-40">Timeout</button></div></td></tr>; })}</tbody></table>{!payroll.isLoading && !payroll.data?.length && <p className="py-8 text-center text-sm text-[var(--text-secondary)]">No payroll records available.</p>}</div></section>
      <section className="rounded-2xl border border-[var(--card-border)] bg-[var(--card-dark)] p-5"><h2 className="text-lg font-semibold">Simulated payment history</h2><div className="mt-3 space-y-2">{payments.data?.map((p) => <div key={p.id} className="flex flex-col justify-between gap-3 rounded-xl border border-[var(--card-border)] p-3 sm:flex-row sm:items-center"><div><p className="font-medium">{p.instructionReference} · {money(p.amount, p.currency)}</p><p className="text-xs text-[var(--text-secondary)]">{paymentStatus(p.status)} · attempt {p.attemptCount}{p.failureReason ? ` · ${p.failureReason}` : ""}</p></div>{String(p.status) === "Delayed" || p.status === 4 ? <button onClick={() => confirm.mutate(p.id)} className="rounded-lg bg-[#C4622D] px-3 py-1 text-xs text-white">Confirm delayed mock payment</button> : null}</div>)}{!payments.isLoading && !payments.data?.length && <p className="text-sm text-[var(--text-secondary)]">No simulated payment attempts yet.</p>}</div></section>
  </main>;
}
