"use client";

import dashboardApi from "@/services/dashboardApi";
import { salaryPayrollApi } from "@/services/salaryPayrollApi";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import type { LucideIcon } from "lucide-react";
import { Banknote,Clock3,Plus,ShieldCheck } from "lucide-react";
import { useState } from "react";

const field = "rounded-lg border border-[var(--card-border)] bg-transparent px-3 py-2 text-sm";
const today = new Date().toISOString().slice(0, 10);
const money = (value: number, currency = "LKR") => new Intl.NumberFormat("en-LK", { style: "currency", currency }).format(value);

export default function OwnerSalaryManagementPage() {
  const client = useQueryClient();
  const departments = useQuery({ queryKey: ["owner-salary-departments"], queryFn: () => dashboardApi.getDepartments() });
  const structures = useQuery({ queryKey: ["salary-structures"], queryFn: salaryPayrollApi.structures });
  const allowances = useQuery({ queryKey: ["salary-allowances"], queryFn: salaryPayrollApi.allowances });
  const payments = useQuery({ queryKey: ["owner-mock-payroll-payments"], queryFn: salaryPayrollApi.payments });
  const [salary, setSalary] = useState({ departmentId: "", employeeRole: "Employee", monthlyBasicSalary: "", overtimeHourlyRate: "", effectiveFrom: today });
  const [allowance, setAllowance] = useState({ departmentId: "", employeeRole: "Employee", employeeId: "", kind: "Transport", calculationType: "FixedAmount", value: "", effectiveFrom: today });
  const [override, setOverride] = useState({ employeeId: "", monthlyBasicSalary: "", overtimeHourlyRate: "", effectiveFrom: today, reason: "" });
  const refresh = async () => { await client.invalidateQueries({ queryKey: ["salary-structures"] }); await client.invalidateQueries({ queryKey: ["salary-allowances"] }); };
  const saveSalary = useMutation({ mutationFn: () => salaryPayrollApi.saveStructure({ ...salary, monthlyBasicSalary: Number(salary.monthlyBasicSalary), overtimeHourlyRate: Number(salary.overtimeHourlyRate), currency: "LKR" }), onSuccess: refresh });
  const saveAllowance = useMutation({ mutationFn: () => salaryPayrollApi.saveAllowance({ ...allowance, departmentId: allowance.employeeId ? undefined : allowance.departmentId, employeeRole: allowance.employeeId ? undefined : allowance.employeeRole, employeeId: allowance.employeeId || undefined, value: Number(allowance.value), currency: "LKR" }), onSuccess: refresh });
  const saveOverride = useMutation({ mutationFn: () => salaryPayrollApi.saveOverride({ ...override, monthlyBasicSalary: Number(override.monthlyBasicSalary), overtimeHourlyRate: override.overtimeHourlyRate ? Number(override.overtimeHourlyRate) : undefined, currency: "LKR" }) });
  const employees = departments.data?.flatMap((d) => d.employees.map((e) => ({ ...e, department: d.name }))) ?? [];
  const cards: { label: string; value: string | number; Icon: LucideIcon }[] = [{ label: "Salary structures", value: structures.data?.length ?? 0, Icon: Banknote }, { label: "Allowance rules", value: allowances.data?.length ?? 0, Icon: Plus }, { label: "Approval authority", value: "Owner only", Icon: ShieldCheck }];

  return <main className="mx-auto max-w-7xl space-y-6 p-6 lg:p-8">
    <header><p className="text-xs uppercase tracking-wider text-[var(--text-secondary)]">Owner controlled · effective-dated revisions</p><h1 className="text-3xl font-bold">Salary Management</h1><p className="mt-1 text-sm text-[var(--text-secondary)]">Configure department roles, allowances and exceptional employee salaries. Every saved change is retained in history.</p></header>
    <section className="grid gap-4 md:grid-cols-3">{cards.map(({ label, value, Icon }) => <div key={label} className="rounded-2xl border border-[var(--card-border)] bg-[var(--card-dark)] p-5"><Icon className="mb-3 h-5 w-5 text-[#E87332]" /><p className="text-xs uppercase text-[var(--text-secondary)]">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></div>)}</section>
    <section className="grid gap-5 xl:grid-cols-2">
      <form onSubmit={(e) => { e.preventDefault(); saveSalary.mutate(); }} className="grid gap-3 rounded-2xl border border-[var(--card-border)] bg-[var(--card-dark)] p-5 md:grid-cols-2"><div className="md:col-span-2"><h2 className="text-lg font-semibold">Department & role salary</h2><p className="text-xs text-[var(--text-secondary)]">New effective dates create immutable revisions.</p></div><select required className={field} value={salary.departmentId} onChange={(e) => setSalary({ ...salary, departmentId: e.target.value })}><option value="">Select department</option>{departments.data?.map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}</select><select className={field} value={salary.employeeRole} onChange={(e) => setSalary({ ...salary, employeeRole: e.target.value })}>{["Admin", "Manager", "Employee"].map((r) => <option key={r}>{r}</option>)}</select><input required min="0.01" step="0.01" type="number" placeholder="Monthly basic salary" className={field} value={salary.monthlyBasicSalary} onChange={(e) => setSalary({ ...salary, monthlyBasicSalary: e.target.value })}/><input required min="0" step="0.01" type="number" placeholder="Overtime hourly rate" className={field} value={salary.overtimeHourlyRate} onChange={(e) => setSalary({ ...salary, overtimeHourlyRate: e.target.value })}/><input required type="date" className={field} value={salary.effectiveFrom} onChange={(e) => setSalary({ ...salary, effectiveFrom: e.target.value })}/><button disabled={saveSalary.isPending} className="rounded-lg bg-[#C4622D] px-4 py-2 text-sm text-white">Approve salary revision</button></form>
      <form onSubmit={(e) => { e.preventDefault(); saveAllowance.mutate(); }} className="grid gap-3 rounded-2xl border border-[var(--card-border)] bg-[var(--card-dark)] p-5 md:grid-cols-2"><div className="md:col-span-2"><h2 className="text-lg font-semibold">Allowance configuration</h2><p className="text-xs text-[var(--text-secondary)]">Fixed LKR or percentage; optionally target one employee.</p></div><select className={`${field} md:col-span-2`} value={allowance.employeeId} onChange={(e) => setAllowance({ ...allowance, employeeId: e.target.value })}><option value="">Department + role allowance</option>{employees.map((e) => <option key={e.id} value={e.id}>Employee: {e.fullName} · {e.department}</option>)}</select><select required={!allowance.employeeId} disabled={Boolean(allowance.employeeId)} className={field} value={allowance.departmentId} onChange={(e) => setAllowance({ ...allowance, departmentId: e.target.value })}><option value="">Select department</option>{departments.data?.map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}</select><select disabled={Boolean(allowance.employeeId)} className={field} value={allowance.employeeRole} onChange={(e) => setAllowance({ ...allowance, employeeRole: e.target.value })}>{["Admin", "Manager", "Employee"].map((r) => <option key={r}>{r}</option>)}</select><select className={field} value={allowance.kind} onChange={(e) => setAllowance({ ...allowance, kind: e.target.value })}>{["Transport", "Meal", "Attendance", "NightShift", "Overtime", "Special"].map((x) => <option key={x}>{x}</option>)}</select><select className={field} value={allowance.calculationType} onChange={(e) => setAllowance({ ...allowance, calculationType: e.target.value })}><option value="FixedAmount">Fixed amount</option><option value="PercentageOfBasic">Percentage of basic</option></select><input required min="0" step="0.01" type="number" placeholder="Allowance value" className={field} value={allowance.value} onChange={(e) => setAllowance({ ...allowance, value: e.target.value })}/><input required type="date" className={field} value={allowance.effectiveFrom} onChange={(e) => setAllowance({ ...allowance, effectiveFrom: e.target.value })}/><button disabled={saveAllowance.isPending} className="rounded-lg bg-[#C4622D] px-4 py-2 text-sm text-white md:col-span-2">Approve allowance rule</button></form>
    </section>
    <form onSubmit={(e) => { e.preventDefault(); saveOverride.mutate(); }} className="grid gap-3 rounded-2xl border border-[var(--card-border)] bg-[var(--card-dark)] p-5 md:grid-cols-3"><div className="md:col-span-3"><h2 className="text-lg font-semibold">Exceptional employee override</h2><p className="text-xs text-[var(--text-secondary)]">Owner approval and a reason are mandatory.</p></div><select required className={field} value={override.employeeId} onChange={(e) => setOverride({ ...override, employeeId: e.target.value })}><option value="">Select employee</option>{employees.map((e) => <option key={e.id} value={e.id}>{e.fullName} · {e.department}</option>)}</select><input required min="0.01" step="0.01" type="number" placeholder="Monthly basic salary" className={field} value={override.monthlyBasicSalary} onChange={(e) => setOverride({ ...override, monthlyBasicSalary: e.target.value })}/><input min="0" step="0.01" type="number" placeholder="Optional overtime rate" className={field} value={override.overtimeHourlyRate} onChange={(e) => setOverride({ ...override, overtimeHourlyRate: e.target.value })}/><input required type="date" className={field} value={override.effectiveFrom} onChange={(e) => setOverride({ ...override, effectiveFrom: e.target.value })}/><input required placeholder="Business reason" className={`${field} md:col-span-2`} value={override.reason} onChange={(e) => setOverride({ ...override, reason: e.target.value })}/><button disabled={saveOverride.isPending} className="rounded-lg bg-[#2F5C52] px-4 py-2 text-sm text-white md:col-span-3">Approve employee override</button></form>
    <section className="rounded-2xl border border-[var(--card-border)] bg-[var(--card-dark)] p-5"><h2 className="flex items-center gap-2 text-lg font-semibold"><Clock3 className="h-5 w-5 text-[#E87332]"/>Revision history</h2><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs uppercase text-[var(--text-secondary)]"><tr><th className="py-2">Department</th><th>Role</th><th>Basic</th><th>Overtime</th><th>Effective</th><th>Revision</th></tr></thead><tbody>{structures.data?.map((s) => <tr key={s.id} className="border-t border-[var(--card-border)]"><td className="py-3">{departments.data?.find((d) => d.id === s.departmentId)?.name ?? s.departmentId}</td><td>{s.employeeRole}</td><td>{money(s.monthlyBasicSalary, s.currency)}</td><td>{money(s.overtimeHourlyRate, s.currency)}/hr</td><td>{s.effectiveFrom}{s.effectiveTo ? ` – ${s.effectiveTo}` : " – current"}</td><td>v{s.revision}</td></tr>)}</tbody></table>{!structures.isLoading && !structures.data?.length && <p className="py-6 text-center text-sm text-[var(--text-secondary)]">No salary structures configured.</p>}</div></section>
    <section className="rounded-2xl border border-[var(--card-border)] bg-[var(--card-dark)] p-5"><h2 className="text-lg font-semibold">Mock payment history</h2><p className="text-xs text-[var(--text-secondary)]">Simulation records only — no bank transfers.</p><div className="mt-3 space-y-2">{payments.data?.map((p) => <div key={p.id} className="flex flex-wrap justify-between gap-2 rounded-xl border border-[var(--card-border)] p-3 text-sm"><span>{p.instructionReference}</span><span>{money(p.amount, p.currency)} · {String(p.status) === "MockPaid" || p.status === 1 ? "Simulated Payment Completed" : String(p.status)}</span></div>)}{!payments.isLoading && !payments.data?.length && <p className="text-sm text-[var(--text-secondary)]">No mock payment history.</p>}</div></section>
  </main>;
}
